### ISSUE TITLE
impl Matrix has several incorrectly implemented functions.

### ISSUE THREAD

**Issue by karshan** [raylib-rs/raylib-rs#35] opened 2024-04-09 00:30 UTC
See: https://github.com/deltaphc/raylib-rs/issues/182

1. Matrix multiplication is backwards if you want a * b you need to write b * a. (this is also true in raylib so maybe this might not be considered a bug, https://github.com/raysan5/raylib/issues/3039)
2. rotate_x, rotate_y, rotate_z return transposed versions of the matrix you want (i.e. these are different from raylib's MatrixRotate{X,Y,Z})

**Comment by IoIxD** [comment] 2024-08-16 03:01
Closing because the latter is now solved and the former is not a bug.

**Closed by IoIxD** 2024-08-16 03:01 UTC
